export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCHING_INGREDIENTS_ERROR = "FETCHING_INGREDIENTS_ERROR";

export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";
export const LOADING_ORDER = "LOADING_ORDER";
export const ORDER_PURCHASED_TRUE = "ORDER_PURCHASED_TRUE";
export const ORDER_PURCHASED_FALSE = "ORDER_PURCHASED_FALSE";
export const ORDER_FETCH_SUCCESS = "ORDER_FETCH_SUCCESS";
export const ORDER_FETCH_FAIL = "ORDER_FETCH_FAIL";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
